### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by mariomeraz** [WataruMaeda/react-firebase-boilerplate#31]
Node Sass version 6.0.1 is incompatible with ^4.0.0 || ^5.0.0.

Iam use node v16.10.0, any idea for fix this.

**Comment by WataruMaeda** [comment]
Hi @mariomeraz , sorry for being late. I guess node 16 is not compatible with the boilerplate. I'll bump the package version asap, thank you.

**Comment by WataruMaeda** [comment]
I'm sorry for being late. Resolved node-sass incompatible issue in the latest version of the template, thanks.

It should work in node v16
